package helpers

// publishing channels
const (
	USERCREATED         = "USERCREATED"
	USERLOGGEDIN        = "USERLOGGEDIN"
	SENDOTP             = "SENDOTP"
	VERIFYEMAIL         = "VERIFYEMAIL"
	UPDATEPHONENUMBER   = "UPDATEPHONENUMBER"
	EMAILVERIFED        = "EMAILVERIFED"
	PHONENUMBERVERIFIED = "PHONENUMBERVERIFIED"
	PASSWORDRESET       = "PASSWORDRESET"
	USERRATED           = "USERRATED"
	ACCOUNTDELETED           = "ACCOUNTDELETED"
)

// subscription channels
const (
	PRODUCTADDED   = "PRODUCTADDED"
	PRODUCTLIKED   = "PRODUCTLIKED"
	PRODUCTUNLIKED = "PRODUCTUNLIKED"
	PRODUCTSAVED   = "PRODUCTSAVED"
	PRODUCTUNSAVED = "PRODUCTUNSAVED"
)
